# preload = ~/.config/Wallpapers/b-445.jpg
preload = ~/.dotfiles/Wallpapers/alive-gl.jpg

preload = ~/.dotfiles/Wallpapers/a9159af9c6dd802c0e5cbcbfb57f030a.jpg

preload = ~/.dotfiles/Wallpapers/pxfuel.jpg


wallpaper = eDP-1,~/.dotfiles/Wallpapers/a9159af9c6dd802c0e5cbcbfb57f030a.jpg
# wallpaper = eDP-1,~/.config/Wallpapers/b-445.jpg
wallpaper = HDMI-A-1,~/.dotfiles/Wallpapers/a9159af9c6dd802c0e5cbcbfb57f030a.jpg
splash = false
